# Generated by Django 5.1.5 on 2025-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, default='https://cdn-icons-png.freepik.com/512/164/164440.png', null=True),
        ),
    ]
